### PR TITLE
Compatibility with Python 3

### PR DESCRIPTION
**Pull request by ihaveamac**
This commit only does the necessary modifications to make it compatible
with Python 3. Future commits would do script cleanup to make it more
readable and "stable".

### CODE REVIEW

**Comment by zoogie** [comment]
Thanks for this. I'm about to add a pretty substantial change to this script, probably today, but I plan on working in your changes somehow. I actually tried to port tadpole to py3 but gave up after about an hour of frustration XD.

**Comment by ihaveamac** [comment]
if you need help working with py3 I can help you somewhere (i'm interested in knowing what you had trouble with).

**Comment by zoogie** [comment]
It was a long while ago, but I think it was type mismatch errors when trying to input strings into the crypto functions.

**Comment by ihaveamac** [comment]
for that case in particular: py3 changed the string types; str is now a unicode string, and bytes is for bytestrings. in py2, str is the bytestring and unicode is for unicode strings. but the really important part is py3 won't automatically and silently convert between the two. py2 usually will and that could cause problems in some cases.

**Comment by ihaveamac** [comment]
I'll make a new pull request in the future to make the new changes work on py3(while keeping 2.7 compatibility). eventually I want to port the other scripts as well.

**Pull request closed without merging**
